ARG NODE_VERSION
FROM node:${NODE_VERSION}-slim AS builder
WORKDIR /app/packages/bot
COPY packages/bot/package.json ./package.json
RUN npm install
COPY packages/bot .
RUN npm run build

FROM node:${NODE_VERSION}-slim AS runner
ARG GIT_SHA
ENV ARBIMIND_BUILD_GIT_SHA=${GIT_SHA}
WORKDIR /app/packages/bot
COPY .nvmrc /app/.nvmrc
COPY pnpm-lock.yaml /app/pnpm-lock.yaml
COPY --from=builder /app/packages/bot/package.json ./package.json
COPY --from=builder /app/packages/bot/node_modules ./node_modules
COPY --from=builder /app/packages/bot/src ./src
COPY --from=builder /app/packages/bot/scripts ./scripts
COPY --from=builder /app/packages/bot/tsconfig.json ./tsconfig.json
CMD ["npm", "start"]
